### ISSUE TITLE
cql "--cg" first argument semantics make it awkward to generate code to an "output" directory

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#113]
The way the cql compiler `--cg` option works makes it difficult to generate code into any directory other than the current working directory.

This is because the first argument to `--cg` is used as both the path to the generated .h file and as the contents of what's #included in the generated .c file. So if the parameter is `"out/file.h"`, then the include line is:

```c
#include "out/file.h"
```

Instead of the desired.

```c
#include "file.h"
```

I can work around this issue by "cd-ing" to the "output" directory before running the cql compiler. But that has the side effect of requiring the paths to all the input files to be modified to be relative to the output directory, which has the side effect that any compiler error messages use the modified relative paths, which means that IDEs (like Visual Studio Code) can't automatically navigate to the error lines, because the paths are incorrect.

A work around for the IDE issue is to make the input files absolute paths, which works, but looks ugly.

**Comment by jackpal** [comment]
(Clicked wrong button. It's still an open issue.)

**Comment by ricomariani** [comment]
I have noticed this before but I don't really know how to fix it.  Maybe an --out-dir option?

**Comment by ricomariani** [comment]
I guess unless they start with "/" or "\" for windows.

**Comment by jackpal** [comment]
Another approach that I think might work would be to add an optional cgl command line argument to specify the full path that's inserted into the `#include` statement. (Similar to the existing `--objc_c_include_path`.)

**Comment by jackpal** [comment]
Sounds good - any way that works is OK with me.

**Comment by ricomariani** [comment]
I finally got around to doing this... Landing shortly.

**Comment by jackpal** [comment]
I updated swiftgen4cgsql to use --c_include_path, and it works great. Thanks for implementing it!

**Comment by ricomariani** [comment]
Awesome!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
