### ISSUE TITLE
Somehow related project "urweb"

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#123]
There is a somehow related project http://www.impredicative.com/ur/ in terms of parsing SQL for applications and their tutorial has an interesting simple format (http://www.impredicative.com/ur/demo/ for example click the `Hello` and on the right bottom frame click any of [ Application | hello.urp | hello.urs | hello.ur ] ) .

I'm bring it here because I think it's useful for people working on this space.

And here is my contribution for the railroad diagram of their language https://github.com/urweb/urweb/issues/248

Cheers !

**Comment by ricomariani** [comment]
I have this a look, there's no specific work needing resolving so I think that's all I owe you to close this issue :D
