### ISSUE TITLE
Nice to have better code generation for prepared statements inside loops

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#125]
When watching this video https://youtu.be/KBu1rbJkCcs?list=PLJE37RiwD_9pvAT-1bpuCx7CGM-Nkwjj0 I noticed that the generated code for prepared statements inside loops are **preparing/binding/finalizing** on every iteration of the loop (see example bellow), the benefit of preparing a statement is to reuse it more than once but the actual generated code is not taking advantage of it.

Also the return code of `cql_prepare` is not checked (it'll be checked inside the `cql_multibind` with an `assert` at runtime).

I wrote an alternative generated code (shown bellow) that uses a missing `cql_resset_stmt` function were the preparation of the statement is outside of the loop (Javascript has this [mis]feature called `hoisting` (https://www.w3schools.com/js/js_hoisting.asp)).

```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  delete from tbl;
  declare ix integer not null;
  declare iy integer not null;
  set ix := 0;
  while ix < nxy
  begin
    set iy := 0;
    while iy < nxy
    begin
      insert into tbl(x, y) values (ix, iy);
      set iy := iy + 1;
    end;
    set ix := ix + 1;
  end;
end;
```
Generated code:
```
// @generated SignedSource<<deadbeef8badf00ddefec8edfacefeed>>
...
CQL_WARN_UNUSED cql_code bulk_load_tbl(sqlite3 *_Nonnull _db_, cql_int32 nxy) {
  cql_code _rc_ = SQLITE_OK;
  cql_int32 ix = 0;
  cql_int32 iy = 0;
  sqlite3_stmt *_temp_stmt = NULL;

  _rc_ = cql_exec(_db_,
    "DELETE FROM tbl");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  ix = 0;
  for (;;) {
  if (!(ix < nxy)) break;
    iy = 0;
    for (;;) {
    if (!(iy < nxy)) break;
      _rc_ = cql_prepare(_db_, &_temp_stmt,
        "INSERT INTO tbl(x, y) VALUES(?, ?)");
      cql_multibind(&_rc_, _db_, &_temp_stmt, 2,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, ix,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, iy);
      if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
      _rc_ = sqlite3_step(_temp_stmt);
      if (_rc_ != SQLITE_DONE) { cql_error_trace(); goto cql_cleanup; }
      cql_finalize_stmt(&_temp_stmt);
      iy = iy + 1;
    }
    ix = ix + 1;
  }
  _rc_ = SQLITE_OK;

cql_cleanup:
  cql_finalize_stmt(&_temp_stmt);
  return _rc_;
}
...
```
One possible alternative generated code:
```
CQL_WARN_UNUSED cql_code bulk_load_tbl(sqlite3 *_Nonnull _db_, cql_int32 nxy) {
  cql_code _rc_ = SQLITE_OK;
  cql_int32 ix = 0;
  cql_int32 iy = 0;
  sqlite3_stmt *_temp_stmt = NULL;

  _rc_ = cql_exec(_db_,
    "DELETE FROM tbl");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  ix = 0;
  _rc_ = cql_prepare(_db_, &_temp_stmt,
     "INSERT INTO tbl(x, y) VALUES(?, ?)");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  for (;;) {
    if (!(ix < nxy)) break;
    iy = 0;
    for (;;) {
    if (!(iy < nxy)) break;
      cql_multibind(&_rc_, _db_, &_temp_stmt, 2,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, ix,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, iy);
      if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
      _rc_ = sqlite3_step(_temp_stmt);
      if (_rc_ != SQLITE_DONE) { cql_error_trace(); goto cql_cleanup; }
      cql_resset_stmt(&_temp_stmt);
      iy = iy + 1;
    }
    ix = ix + 1;
  }
  _rc_ = SQLITE_OK;

cql_cleanup:
  cql_finalize_stmt(&_temp_stmt);
  return _rc_;
}
```

**Comment by mingodad** [comment]
When adding **begin/commit** wrapping the loop if there is an error there is no **rollback** and the database will be **locked**:
```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  delete from tbl;
  begin;
  declare ix integer not null;
  declare iy integer not null;
  set ix := 0;
  while ix < nxy
  begin
    set iy := 0;
    while iy < nxy
    begin
      insert into tbl(x, y) values (ix, iy);
      set iy := iy + 1;
    end;
    set ix := ix + 1;
  end;
  commit;
end;
```
Generated code:
```
CQL_WARN_UNUSED cql_code bulk_load_tbl(sqlite3 *_Nonnull _db_, cql_int32 nxy) {
  cql_code _rc_ = SQLITE_OK;
  cql_int32 ix = 0;
  cql_int32 iy = 0;
  sqlite3_stmt *_temp_stmt = NULL;

  _rc_ = cql_exec(_db_,
    "DELETE FROM tbl");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  _rc_ = cql_exec(_db_,
    "BEGIN");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  ix = 0;
  for (;;) {
  if (!(ix < nxy)) break;
    iy = 0;
    for (;;) {
    if (!(iy < nxy)) break;
      _rc_ = cql_prepare(_db_, &_temp_stmt,
        "INSERT INTO tbl(x, y) VALUES(?, ?)");
      cql_multibind(&_rc_, _db_, &_temp_stmt, 2,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, ix,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, iy);
      if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
      _rc_ = sqlite3_step(_temp_stmt);
      if (_rc_ != SQLITE_DONE) { cql_error_trace(); goto cql_cleanup; }
      cql_finalize_stmt(&_temp_stmt);
      iy = iy + 1;
    }
    ix = ix + 1;
  }
  _rc_ = cql_exec(_db_,
    "COMMIT");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  _rc_ = SQLITE_OK;

cql_cleanup:
  cql_finalize_stmt(&_temp_stmt);
  return _rc_;
}
```

**Comment by mingodad** [comment]
After writing the previous message I remember something about **abort** and looking at the documentation we can have **rollback** in case of failing (also **abort/fail/ignore/replace/rollback**) and reading this blog post https://cgsql.dev/blog/flow-analysis it seems a case like this be a good candidate for the **flow analizer** check if when there is an explicit **transaction** there is also management for **error/rollback/commit**.
```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  delete from tbl;
  begin;
  declare ix integer not null;
  declare iy integer not null;
  set ix := 0;
  while ix < nxy
  begin
    set iy := 0;
    while iy < nxy
    begin
      insert or ROLLBACK into tbl(x, y) values (ix, iy);
      set iy := iy + 1;
    end;
    set ix := ix + 1;
  end;
  commit;
end;
```
Generated code:
```
CQL_WARN_UNUSED cql_code bulk_load_tbl(sqlite3 *_Nonnull _db_, cql_int32 nxy) {
  cql_code _rc_ = SQLITE_OK;
  cql_int32 ix = 0;
  cql_int32 iy = 0;
  sqlite3_stmt *_temp_stmt = NULL;

  _rc_ = cql_exec(_db_,
    "DELETE FROM tbl");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  _rc_ = cql_exec(_db_,
    "BEGIN");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  ix = 0;
  for (;;) {
  if (!(ix < nxy)) break;
    iy = 0;
    for (;;) {
    if (!(iy < nxy)) break;
      _rc_ = cql_prepare(_db_, &_temp_stmt,
        "INSERT OR ROLLBACK INTO tbl(x, y) VALUES(?, ?)");
      cql_multibind(&_rc_, _db_, &_temp_stmt, 2,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, ix,
                    CQL_DATA_TYPE_NOT_NULL | CQL_DATA_TYPE_INT32, iy);
      if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
      _rc_ = sqlite3_step(_temp_stmt);
      if (_rc_ != SQLITE_DONE) { cql_error_trace(); goto cql_cleanup; }
      cql_finalize_stmt(&_temp_stmt);
      iy = iy + 1;
    }
    ix = ix + 1;
  }
  _rc_ = cql_exec(_db_,
    "COMMIT");
  if (_rc_ != SQLITE_OK) { cql_error_trace(); goto cql_cleanup; }
  _rc_ = SQLITE_OK;

cql_cleanup:
  cql_finalize_stmt(&_temp_stmt);
  return _rc_;
}
```

**Comment by mingodad** [comment]
Also reading the documentation and viewing the generated code I can see that only the **SQLITE_OK** is checked so in case of **FAIL** it should continue processing the loop, so the error check will become a bit more **involved/trick**.

**Comment by ricomariani** [comment]
multibind has this loop

for (cql_int32 i = 0; *prc == SQLITE_OK && i < count; i++) {
...
}

It's a no-op if the prepare failed.  This is done to save tests.

**Comment by ricomariani** [comment]
Generally the cql runtime takes the position that anything other than SQLITE_OK is fatal.  Except when stepping where you can get SQLITE_ROW and such.

**Comment by ricomariani** [comment]
cql_prepare can do caching or not, it's replacable.  The default runtime does no caching.  The one we use with messenger does.  The default runtime is silent on caching because it has no way to know what a good policy might be for your application.  But it's very easy to replace cql_prepare with something that caches.  There's a section on this sort of thing in the relevant appendix.  See https://cgsql.dev/cql-guide/x11

**Comment by ricomariani** [comment]
With regards to transactions, CQL is again silent on when to abort or rollback with the exception of the

PROC SAVEPOINT
BEGIN
  ...
END;

Construct which gives you good flow control.

Otherwise we take the same position as SQLite does which is, it's up to you to clean up your transactions.  I I strongly recommend PROC SAVEPOINT as it is much less error prone.  

#define TRANSACTION DO NOT EVEN DO THIS

Can be wise :D

**Comment by ricomariani** [comment]
Did I miss anything? :D

**Comment by mingodad** [comment]
Thank you for all your comments, help and sorry by the noise !
I'm diving a bit more on the documentation that has a lot to be digested.

**Comment by mingodad** [comment]
**Is this the expected way of using `WITH RECURSIVE` in `CQL` or should it accept the one `sqlite3` accepts too ?**
Continuing with my tests of code generation from `CQL` I created the example bellow:
```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  proc savepoint
  begin
		delete from tbl;
		--begin;
		WITH RECURSIVE
			ix(xn) AS (VALUES(1) UNION ALL SELECT xn+1 FROM ix WHERE xn<nxy),
			iy(yn) AS (VALUES(1) UNION ALL SELECT yn+1 FROM iy WHERE yn<nxy)
			insert or ROLLBACK into tbl(x, y)
				select ix.xn, iy.yn
				from ix join iy;
		--commit;
	end;
end;
```
Then I've got this error:
```
cql --ast --echo --nolines --cg lopp-with-pp2.h lopp-with-pp2.c  --in lopp-with-pp2.cql
lopp-with-pp2.cql:13:1: error: in select_core : CQL0058: if multiple selects, all column names must be identical so they have unambiguous names; error in column 1: 'column1' vs. '_anon'
semantic errors present; no code gen.
```
Tested this in sqlite3 and it works:
```
WITH RECURSIVE
	ix(xn) AS (VALUES(1) UNION ALL SELECT xn+1 FROM ix WHERE xn<2),
	iy(yn) AS (VALUES(1) UNION ALL SELECT yn+1 FROM iy WHERE yn<2)
	--insert or ROLLBACK into tbl(x, y)
		select ix.xn, iy.yn
		from ix join iy;
```
Output of sqlite3:
```
sqlite3 < "test.sql"
1|1
1|2
2|1
2|2
```
Then after trying several changes to allow `CQL` accept it I came to this that does what I was expecting:
```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  proc savepoint
  begin
		delete from tbl;
		--begin;
		WITH RECURSIVE
			ix(xn) AS (select 1 as xn UNION ALL SELECT ix.xn+1 as xn FROM ix WHERE ix.xn<nxy),
			iy(yn) AS (select 1 as yn UNION ALL SELECT iy.yn+1 as yn FROM iy WHERE iy.yn<nxy)
			insert or ROLLBACK into tbl(x, y)
				select ix.xn, iy.yn
				from ix join iy;
		--commit;
	end;
end;
```

**Comment by mingodad** [comment]
Searching for `CQL0058` I found it in two places, then I searched for `CQL0` and found some other duplicated instances but overall it seems that the idea was to uniquely identify where the error was generated and those duplicated instances seem to be due to **copy and paste**.
Am I wrong here ?

**Comment by mingodad** [comment]
Also with the command line I'm using there is no `AST` output and no warning/error about the omission:
```
>cql --ast --echo --nolines --cg lopp-with-pp.h lopp-with-pp.c  --in lopp-with-pp.cql
>Exit code: 0
```

**Comment by mingodad** [comment]
The problems with `CQL0058` error was the `VALUES(1)` but because I started replacing form right to left only when I've got to the `VALUES(1)` CQL accepted it, reading the `guide.html` section `Using WITH RECURSIVE` doesn't mention this restriction and asking to only dump the AST `--ast` it shows the AST tree properly parsed. 
```
create table tbl(
  x integer not null,
  y integer not null
);

create proc bulk_load_tbl(nxy integer not null)
begin
  proc savepoint
  begin
		delete from tbl;
		--begin;
		WITH RECURSIVE
			ix(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM ix WHERE n<nxy),
			iy(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM iy WHERE n<nxy)
			insert or ROLLBACK into tbl(x, y)
				select ix.n, iy.n
				from ix join iy;
		--commit;
	end;
end;
```

**Comment by mingodad** [comment]
After using the reformatted source provided by CQL the error message point specifically to `UNION ALL` and give better clue:
```
create table tbl(
  x integer not null,
  y integer not null
);

CREATE PROC bulk_load_tbl (nxy INTEGER NOT NULL)
BEGIN
  PROC SAVEPOINT
  BEGIN
    DELETE FROM tbl;
    WITH RECURSIVE
    ix (n) AS (VALUES(1)
    UNION ALL --error: in select_core : CQL0058: if multiple selects, all column names must be identical
    SELECT n + 1
      FROM ix
      WHERE n < nxy),
    iy (n) AS (SELECT 1
    UNION ALL
    SELECT n + 1
      FROM iy
      WHERE n < nxy)
    INSERT OR ROLLBACK INTO tbl(x, y) SELECT ix.n, iy.n
      FROM ix
      INNER JOIN iy;
  END;
END;
```
```
cql --ast --echo --nolines --cg lopp-with-pp2.h lopp-with-pp2.c  --in lopp-with-pp2.cql
lopp-with-pp2.cql:13:1: error: in select_core : CQL0058: if multiple selects, all column names must be identical so they have unambiguous names; error in column 1: 'column1' vs. '_anon'
semantic errors present; no code gen.
```

**Comment by mingodad** [comment]
But in this example from `guide.html` it does accept `VALUES(1) UNION ALL SELECT 1 AS column1` without error, and doing experiments it seems that is due to using `AS column1` because any other name gives an error as before, the `guide.html` doesn't mention the special significance of this names.
```
create table T3(
  id integer not null
);

CREATE PROC insert_compound ()
BEGIN
	INSERT INTO T3(id) VALUES(1)
	UNION ALL
	SELECT 1 AS column1;
END;
```

**Comment by ricomariani** [comment]
We've drifted from the original question.

What's happening to you here is that sqlite is a lot looser than CQL on lots of things.  One of this UNION ALL and friends.

This is legal sqlite

```
select 1
union all
select 'x'

```

It's not legal in CQL, the types don't match and the columns aren't named.  "Column1" has no significance it could have been "foo".

If you do union all the column names all have to match.  Unnamed columns get a synthetic name like "_anon1". 

So in CQL this is correct:

select 'x' foo
union all
select 'y' foo

This prevents a lot of errors.

With recursive will have the same issues.

**Comment by ricomariani** [comment]
Oh there is something special going on there, in a VALUES statement, the implied column names are column1, column2, etc.  This doesn't actually help you at all other than if you have values in one branch of a union you can meet the "same name" rule by matching the column.

But this is really a lot better:

```
CREATE PROC bulk_load_tbl (nxy INTEGER NOT NULL)
BEGIN
  PROC SAVEPOINT
  BEGIN
    DELETE FROM tbl;

    WITH RECURSIVE
    ix (*) AS (
      select 1 xn
      UNION ALL
      SELECT xn + 1 xn FROM ix WHERE ix.xn < nxy
    ),
    iy (*) AS (
      select 1 yn
      UNION ALL
      SELECT yn + 1 yn FROM iy WHERE iy.yn < nxy
    )
    INSERT OR ROLLBACK INTO tbl(x, y) SELECT ix.xn, iy.yn
      FROM ix
      INNER JOIN iy;
  END;
END;
```

In sql you can make a CTE like so

```
WITH
foo(*) as (select 1 x, 2 y)
...
```

The (*) syntax means "get the names from the column names of the select" which is much less error prone than trying to match them all.  There are lots of places in the language where CQL provides alternatives to the error prone `(long list of columns) (long list of values that have to match)`

**Comment by ricomariani** [comment]
CQL0058 can happen in two ways, it's basically the same error.


```
create proc foo(x bool)
begin
  if x then
    select 5 foo;
  else
    select 'x' bar;
  end if;
end;
```

Or:

```
create proc foo()
begin
    select 5 foo;
  union all
    select 'x' bar;
end;
```

**Comment by ricomariani** [comment]
BTW this also works:

```
@attribute(cql:shared_fragment)
create proc numbers(lim_ int not null)
BEGIN
  WITH numbers(*) AS (
    SELECT 1 n
    UNION ALL
    SELECT n + 1 AS n FROM numbers WHERE numbers.n < lim_
  )
  SELECT * from numbers;
END;

CREATE PROC bulk_load_tbl (nxy INTEGER NOT NULL)
BEGIN
  PROC SAVEPOINT
  BEGIN
    DELETE FROM tbl;

    with
    ix(*) as (CALL numbers(nxy)),
    iy(*) as (CALL numbers(nxy))
    INSERT OR ROLLBACK INTO tbl(x, y)
      SELECT ix.n, iy.n FROM ix INNER JOIN iy;
  END;
END;
```

**Comment by ricomariani** [comment]
I think I ran everything down here even though this drifted a lot.

**Comment by ricomariani** [comment]
If there is something I missed please open a separate issue for it so it's clear.  Like hoist it outta here.  I did try my best to find everything/anything that needed a fix.

**Comment by mingodad** [comment]
> Inside me I hear a voice saying:
> 
> Having a code generator for `Lua`, building `cql` static linked with `Lua` and `sqlite3` outputing it to wasm would create a nice **online playground**, and allowing `Lua` to create `sqlite3` functions too would be the cherry on top of it.

Initial online playground announce here https://github.com/facebookincubator/CG-SQL/issues/164
