### ISSUE TITLE
facebook version of  CG/SQL is no longer pushing commits (unlinked from internal)

### ISSUE THREAD

**Issue by ricomariani** [facebookincubator/CG-SQL#176]
I have created a public fork based on the last state and I'm fixing the internal links and stuff in the docs gradually.

I will continue to maintain this fork which I'm calling the Author's Cut.

[README](https://ricomariani.github.io/CG-SQL-author/)

I'm using github pages for the few things that must be html (e.g. railroad diagrams) but the rest I'm just going to leave as markdown docs in preview mode at least for now.

[Guide](https://github.com/ricomariani/CG-SQL-author/blob/main/CQL_Guide/generated/guide.md)
[Internals](https://github.com/ricomariani/CG-SQL-author/blob/main/CQL_Guide/generated/internal.md)

[Root](https://github.com/ricomariani/CG-SQL-author/tree/main)

**Comment by mingodad** [comment]
Hello @ricomariani thanks for going forward with this project !
There is some small fixes here https://github.com/facebookincubator/CG-SQL/issues/164#issuecomment-1356163121 that  you could include.

Cheers !

**Comment by ricomariani** [comment]
I pulled in as many of those suggestions as I could, some were already fixed.  I didn't pull in the 32 bit fixes because frankly I have no expectation that the thing works at all when compiled with 32 bit ints.  The warnings are the least of it I think.  I have no 32 bit compiler available to test against and I'm not that interested in doing the port anyway.  I'll take pull requests if you like :D.  For starters the symbol table ->val thing needs to be a union if it's going to work at all.
