### ISSUE TITLE
Usage of cql on the documentation could be on top

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#63]
Looking through the documentation at https://cgsql.dev/cql-guide/ch13/ to find how to output `json` we need to a do long scroll to the bottom to be able to see how to invoke `cql` to output `json` I think that having it at the beginning/top would make it easier to use.

**Comment by ricomariani** [comment]
I'm happy to make this change for you but you can also edit ch13.md yourself.  I'm happy to take PRs for docs!  VERY HAPPY!  :D

**Comment by ricomariani** [comment]
https://cgsql.dev/cql-guide/x1  can be helpful too

**Comment by ricomariani** [comment]
done
