### ISSUE TITLE
Memory exausted

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#65]
After seeing the discussion on sqlite forum about operators precedence/associativity I went looking for tests done by other people to use then.
I found this project https://github.com/ArashPartow/exprtk with a good amount of tests and after adapt some of then to sqlite and run it successfully I tried to see how `cql` would parse it and I got this error:
```
./cql < exprtk_functional_test.txt.sql 
Error at <stdin>:5005 : memory exhausted
Parse errors found, no further passes will run.
Command exited with non-zero status 2
0.04user 0.00system 0:00.04elapsed 100%CPU (0avgtext+0avgdata 17804maxresident)k
0inputs+0outputs (0major+4006minor)pagefaults 0swaps
```
[exprtk_functional_test.txt.sql.zip](https://github.com/facebookincubator/CG-SQL/files/6836095/exprtk_functional_test.txt.sql.zip)

**Comment by mingodad** [comment]
After reading the bison documentation at https://www.gnu.org/software/bison/manual/html_node/Recursion.html and changing `cql.y` as shown bellow it does parse the whole file.
```
-------------------------------- sources/cql.y --------------------------------
index 95e5230d..2ac3c51f 100644
@@ -298,7 +298,7 @@ opt_stmt_list:
 
 stmt_list[result]:
   stmt ';'  { $result = new_ast_stmt_list($stmt, NULL); $result->lineno = $stmt->lineno;}
-  | stmt ';' stmt_list[slist]  { $result = new_ast_stmt_list($stmt, $slist); $result->lineno = $stmt->lineno; }
+  | stmt_list[slist] stmt ';'  { $result = new_ast_stmt_list($stmt, $slist); $result->lineno = $stmt->lineno; }
   ;
 
 stmt:

**Comment by mingodad** [comment]
But the output sql is in reverse order !

**Comment by mingodad** [comment]
Probably with a different `new_ast_stmt_list` that adds new nodes at the `tail`, I see that they are defined by macros and probably one already exists but I not yet familiar with then.

**Comment by mingodad** [comment]
There are other places that use right recursion, probably an overal revision/refactoring would be needed.

**Comment by ricomariani** [comment]
I made this change:

```
/* We're going to do this cheesy thing with the stmt_list structures so that we can
   code the stmt_list rules using right recursion.  We're doing this because it's
   possible that there could be a LOT of statements and this minimizes the use
   of the bison stack because reductions happen sooner with this pattern.  It does
   mean we have to do some weird stuff because we need to build the list so that the
   tail is on the right.  To accomplish this we take advantage of the fact that the
   parent pointer of the statement list is meaningless while it is unrooted.  It
   would always be null.  We store the tail of the statement list there so we know
   where to add new nodes on the right.  When the statement list is put into the tree
   the parent node is set as usual so nobody will know we did this and we don't
   have to add anything to the node for this one case.

   With this done we can handle several thousand statements without using much stack space.
*/
stmt_list[result]:
  stmt ';'  { 
     $result = new_ast_stmt_list($stmt, NULL);
     $result->lineno = $stmt->lineno;
     // set up the tail pointer invariant to use later
     $result->parent = $result; }
  | stmt_list[slist] stmt ';'  { 
     ast_node *new_stmt = new_ast_stmt_list($stmt, NULL); new_stmt->lineno = $stmt->lineno;

     // use our tail pointer invariant
     ast_node *tail = $slist->parent;  

     ast_set_right(tail, new_stmt);

     // re-establish the tail invariant
     $slist->parent = new_stmt;
     $result = $slist; }
  ;
 ```
 
 Right recursion is markedly less convenient and really it only matters when the chain can be very long indeed.  For instance we could hit the same issue with columns in tables but as a practical matter bisons limits are sufficiently high that we just are never having that many columns in a table.  If you can think of any others with unbounded list by all means point them out.  The above trick generalizes.
