### ISSUE TITLE
Missing semicolon on parser cq.y ?

### ISSUE THREAD

**Issue by mingodad** [facebookincubator/CG-SQL#8]
While implementing this https://github.com/facebookincubator/CG-SQL/pull/6/files I noticed that apparently there is a missing semicolon in several places (judging by the indentation) and if I'm right they are fixed there:
```
opt_stmt_list: /*nil*/ { $$ = NULL; }
  | stmt_list { $$ = $1; }
  ; ////!!!!! missing

stmt_list: stmt ';' { $$ = new_ast_stmt_list($1, NULL); $$->lineno = $1->lineno;}
```
```
stmt: misc_attrs any_stmt { $$ = $1 ? new_ast_stmt_and_attr($1, $2) : $2; }
  ; ////!!!!! missing

any_stmt: select_stmt
```
```
window_name_defn: name AS window_defn { $$ = new_ast_window_name_defn($1, $3); }
  ; ////!!!!! missing

region_spec:
    name  { $$ = new_ast_region_spec($1, new_ast_opt(PUBLIC_REGION)); }

```

**Comment by mingodad** [comment]
This is not critical but it makes easier to parse it using regular expressions like with this script (https://github.com/mingodad/squilu/blob/master/SquiLu/samples/cvt-bison-to-named.nut) I used to help create this https://github.com/facebookincubator/CG-SQL/pull/6/files

**Comment by ricomariani** [comment]
A lot of these leaked in. Bison doesn't give you an error when you do this.  I can make another pass on this.
