### ISSUE TITLE
None of the tutorials that call printf compile (CQL0323)

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#91]
Repro steps:

+ M1 Macbook Pro running MacOS 12.1
+ Install homebrew 3.0
+ Install fex, bison as directed by cg-sql docs
+ Build cgl app
+ Start working through the [cql guide tutorials](https://cgsql.dev/cql-guide/ch01)

```
$ cat  hello.sql
create proc hello()
begin
  call printf("Hello, world\n");
end;
$ cql --in hello.sql --cg hello.h hello.c
hello.sql:3:1: error: in call_stmt : CQL0323: calls to undeclared procedures are forbidden; declaration missing or typo 'printf'
semantic errors present; no code gen.```
```

Updating all the sql examples to include this line at the top seemed to fix the issue:

```
declare procedure printf no check;
```

**Comment by ricomariani** [comment]
If you have a set of fixes I'd be happy to take PR.  If not I can go through them myself.

**Comment by ricomariani** [comment]
CQL0323 was added some time ago because errors were starting to creep into user code with undeclared procedures, but the tutorial never got updated.

**Comment by jackpal** [comment]
If it's not too much trouble, I'd just as soon that you made the fix.

I need to read up on my company's open source policy before signing the project CLA. I think it's fine, but I need to make sure. I'm certain that it's OK for me to file Issues. :-) !

**Comment by ricomariani** [comment]
No problemo.  This is easy stuff to fix.  I'll get to that on Monday :D

**Comment by ricomariani** [comment]
fix for this is set to land shortly

**Comment by ricomariani** [comment]
All fixed :D
