### ISSUE TITLE
Minor doc issue: build instructions should document what directory to build in

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#94]
This is a small issue, but I think it is still worth fixing:

The how-to-build document, https://cgsql.dev/docs/building,  explains how to build cgl, but doesn't mention what directory to build in.

(I believe you have to be in the sources/ directory for the instructions to work. Similarly for ./test.sh and ./cov.sh )

**Comment by ricomariani** [comment]
Good idea

**Comment by ricomariani** [comment]
Feel free to submit PRs for this stuff if you want.  I'm happy to take doc updates!

**Comment by ricomariani** [comment]
All done!
