### ISSUE TITLE
Request: Allow declaring and using variadic select procedures like json_extract

### ISSUE THREAD

**Issue by jackpal** [facebookincubator/CG-SQL#98]
The [JSON1](https://www.sqlite.org/json1.html) extension has some variadic functions, such as `json_extract`. These functions are hard to call from cgl, because you have to declare how many arguments they have.

They also have variable return types, but in many cases that can be dealt with using CAST(json_extract(...) AS INT).

Maybe you could add a "no check" decoration for "select" procedures?

Or, since JSON1's such a popular extension it might be worth building knowledge of it into cg-sql, similar to how SQLite's built in printf() is handled.

**Comment by ricomariani** [comment]
Adding builtin support for SQLite's json_extract seems like a good idea.

**Comment by ricomariani** [comment]
I haven't forgotten about this :D
